[package]
name = "anise"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Core of the ANISE library"

[dependencies]
hifitime = "3.8.6"
memmap2 = "=0.9.3"
crc32fast = "=1.3.2"
der = { version = "0.7.8", features = ["derive", "alloc", "real"] }
clap = { version = "4", features = ["derive"] }
log = "=0.4"
pretty_env_logger = "=0.5"
tabled = "=0.15"
const_format = "0.2"
nalgebra = "0.32"
approx = "=0.5.1"
zerocopy = { version = "0.7.26", features = ["derive"] }
bytes = "=1.5.0"
snafu = { version = "0.7.5", features = ["backtrace"] }
lexical-core = "0.8.5"
heapless = "0.8.0"
rstest = "0.18.2"
# eframe = { version = "0.24.0", optional = true }
# egui = { version = "0.24.0", optional = true }
# egui_extras = { version = "0.24.0", features = [
#     "datepicker",
#     "http",
#     "image",
# ], optional = true }
# egui-toast = { version = "0.10.0", optional = true }
# rfd = { version = "0.12.1", optional = true }

# [target.'cfg(target_arch = "wasm32")'.dependencies]
# wasm-bindgen-futures = "0.4"
# poll-promise = { version = "0.3.0", features = ["web"] }

[dev-dependencies]
rust-spice = "0.7.6"
parquet = "49.0.0"
arrow = "49.0.0"
criterion = "0.5"
iai = "0.1"
polars = { version = "0.35.0", features = ["lazy", "parquet"] }
rayon = "1.7"

[[bench]]
name = "iai_jpl_ephemerides"
harness = false

[[bench]]
name = "crit_jpl_ephemerides"
harness = false

[[bench]]
name = "crit_spacecraft_ephemeris"
harness = false

[[bench]]
name = "crit_bpc_rotation"
harness = false
