name: Benchmarks

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  ephem_type2_chebyshev:
    name: SPICE versus ANISE Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        
      - name: Download data
        run: |
          wget -O data/de421.bsp http://public-data.nyxspace.com/anise/de421.bsp
          wget -O data/de430.bsp http://public-data.nyxspace.com/anise/de430.bsp
          wget -O data/de440s.bsp http://public-data.nyxspace.com/anise/de440s.bsp
          wget -O data/de440.bsp http://public-data.nyxspace.com/anise/de440.bsp
          wget -O data/pck08.pca http://public-data.nyxspace.com/anise/pck08.pca
          wget -O data/gmat-hermite.bsp http://public-data.nyxspace.com/anise/ci/gmat-hermite.bsp
          wget -O data/variable-seg-size-hermite.bsp http://public-data.nyxspace.com/anise/ci/variable-seg-size-hermite.bsp
          wget -O data/earth_latest_high_prec.bpc http://public-data.nyxspace.com/anise/ci/earth_latest_high_prec-2023-09-08.bpc

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install CSPICE
        run: sh dev-env-setup.sh && cd .. # Return to root

      - name: Bench JPL Ephemerides
        run: cargo bench --bench "*_jpl_ephemerides" --workspace --exclude anise-py
      
      - name: Bench Spacecraft (Hermite type 13)
        run: cargo bench --bench "*_spacecraft_ephemeris" --workspace --exclude anise-py
      
      - name: Bench Binary planetary constants
        run: cargo bench --bench "crit_bpc_rotation" --workspace --exclude anise-py

      - name: Save benchmark artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jpl-development-ephemerides-benchmark
          path: target/criterion/**/report/*
